#!/usr/bin/env ruby

require 'fileutils'

# maybe use a tmp directory instead?
FileUtils.rm_rf('unzipped')
FileUtils.mkdir_p('unzipped')

apps_pattern = File.join(ENV['HOME'], 'Music', 'iTunes', 'Mobile Applications', '*.ipa')

doc = ''
Dir[apps_pattern].each do |app_file|
  app_name = File.basename(app_file, '.ipa')
  unzip_dir = File.join('unzipped', app_name)
  plist = File.join(unzip_dir, 'iTunesMetadata.plist')
  
  # maybe do this in Ruby?
  `unzip -d "#{unzip_dir}" "#{app_file}" iTunesMetadata.plist`
  `chmod +rw "#{plist}"`
  `plutil -convert xml1 "#{plist}"`
  
  File.open(plist) do |file|
    file.readline
    file.readline
    doc << file.read
  end
  
end

FileUtils.rm_rf('unzipped')

require 'net/http'
require 'uri'

response = Net::HTTP.post_form(URI.parse('http://installd.local/users/floehopper/installs/synchronize'), { '_method' => 'put', 'doc' => doc })
success = (response.code == '200')
p success

